"""Compact SkillsFuture-style sample data for the hackathon demo.

Schema mirrors fields in the official Skills Framework datasets: sector, role,
key tasks, technical skills, critical core skills, proficiency, and source notes.
Replace or extend this module from the official Q2 2026 spreadsheets when needed.
"""

ROLES = [
    {
        "id": "data-analyst",
        "title": "Data Analyst",
        "sector": "ICT / Business Analytics",
        "level": "Associate",
        "summary": "Turns operational data into dashboards, insights and decisions.",
        "tasks": ["Profile datasets", "Build dashboards", "Explain trends", "Automate recurring reports"],
        "skills": ["Data Analysis", "SQL", "Data Visualisation", "Spreadsheet Modelling", "Statistical Thinking", "Stakeholder Communication"],
        "core_skills": ["Communication", "Sense Making", "Problem Solving"],
        "proficiency": {"Data Analysis": 3, "SQL": 3, "Data Visualisation": 3, "Stakeholder Communication": 2},
        "source": "SkillsFuture Skills Framework-style sample, Q2 2026 demo schema",
    },
    {
        "id": "ai-product-analyst",
        "title": "AI Product Analyst",
        "sector": "ICT / Product",
        "level": "Intermediate",
        "summary": "Connects product metrics, user research and AI evaluation to improve AI products safely.",
        "tasks": ["Define AI product metrics", "Evaluate model outputs", "Run user experiments", "Prioritise product improvements"],
        "skills": ["Data Analysis", "AI Literacy", "Prompt Evaluation", "Product Analytics", "Experiment Design", "User Research", "Responsible AI"],
        "core_skills": ["Communication", "Creative Thinking", "Decision Making", "Sense Making"],
        "proficiency": {"AI Literacy": 3, "Prompt Evaluation": 3, "Product Analytics": 3, "Responsible AI": 2},
        "source": "Synthesised from AI product and analytics role patterns for hackathon demo",
    },
    {
        "id": "python-automation-specialist",
        "title": "Python Automation Specialist",
        "sector": "ICT / Operations",
        "level": "Intermediate",
        "summary": "Automates repetitive business workflows with Python scripts, APIs and robust checks.",
        "tasks": ["Map manual workflows", "Integrate APIs", "Write Python automations", "Monitor failures"],
        "skills": ["Python Programming", "API Integration", "Workflow Automation", "Testing", "Data Cleaning", "Documentation"],
        "core_skills": ["Problem Solving", "Collaboration", "Adaptability"],
        "proficiency": {"Python Programming": 3, "API Integration": 3, "Testing": 2, "Documentation": 2},
        "source": "SkillsFuture-style automation role sample",
    },
    {
        "id": "cybersecurity-analyst",
        "title": "Cybersecurity Analyst",
        "sector": "ICT / Cybersecurity",
        "level": "Associate",
        "summary": "Monitors threats, investigates incidents and strengthens baseline controls.",
        "tasks": ["Triage security alerts", "Investigate incidents", "Document vulnerabilities", "Improve controls"],
        "skills": ["Cybersecurity Operations", "Log Analysis", "Risk Assessment", "Incident Response", "Python Programming", "Technical Writing"],
        "core_skills": ["Problem Solving", "Sense Making", "Communication"],
        "proficiency": {"Cybersecurity Operations": 3, "Log Analysis": 3, "Incident Response": 2, "Risk Assessment": 2},
        "source": "SkillsFuture-style cybersecurity sample",
    },
    {
        "id": "cloud-data-engineer",
        "title": "Cloud Data Engineer",
        "sector": "ICT / Cloud & Data",
        "level": "Intermediate",
        "summary": "Builds reliable data pipelines and cloud data products for analytics and AI teams.",
        "tasks": ["Design data pipelines", "Operate cloud storage", "Automate data quality checks", "Document data contracts"],
        "skills": ["Python Programming", "SQL", "Cloud Platforms", "Data Engineering", "Data Quality", "Testing", "API Integration"],
        "core_skills": ["Problem Solving", "Collaboration", "Digital Fluency"],
        "proficiency": {"Data Engineering": 3, "Cloud Platforms": 3, "SQL": 3, "Data Quality": 2},
        "source": "SkillsFuture-style cloud data sample",
    },
    {
        "id": "learning-experience-designer",
        "title": "Learning Experience Designer",
        "sector": "Training & Adult Education",
        "level": "Intermediate",
        "summary": "Designs learner-centred programmes, assessments and coaching journeys.",
        "tasks": ["Analyse learner needs", "Design learning journeys", "Create assessments", "Evaluate learning outcomes"],
        "skills": ["Learning Needs Analysis", "Curriculum Design", "Facilitation", "Assessment Design", "User Research", "Data Visualisation"],
        "core_skills": ["Communication", "Creative Thinking", "Collaboration"],
        "proficiency": {"Learning Needs Analysis": 3, "Curriculum Design": 3, "Assessment Design": 2, "User Research": 2},
        "source": "Training and adult education framework-style sample",
    },
    {
        "id": "sustainability-data-coordinator",
        "title": "Sustainability Data Coordinator",
        "sector": "Green Economy / Corporate Services",
        "level": "Associate",
        "summary": "Collects ESG data, validates evidence and supports sustainability reporting.",
        "tasks": ["Collect ESG metrics", "Validate evidence", "Prepare reports", "Coordinate departments"],
        "skills": ["Data Analysis", "Spreadsheet Modelling", "Sustainability Reporting", "Stakeholder Communication", "Data Quality", "Documentation"],
        "core_skills": ["Communication", "Collaboration", "Sense Making"],
        "proficiency": {"Sustainability Reporting": 2, "Data Analysis": 2, "Data Quality": 2, "Stakeholder Communication": 3},
        "source": "Green skills and corporate reporting demo sample",
    },
]

SAMPLE_LEARNERS = {
    "operations-coordinator": {
        "label": "Operations coordinator moving into data/automation",
        "current_role": "Operations Coordinator",
        "skills": ["Spreadsheet Modelling", "Stakeholder Communication", "Documentation", "Problem Solving", "Data Cleaning"],
        "interests": ["less manual reporting", "clear career ladder", "Python"],
        "hours_per_week": 5,
    },
    "marketing-exec": {
        "label": "Marketing executive exploring AI product roles",
        "current_role": "Marketing Executive",
        "skills": ["User Research", "Stakeholder Communication", "Data Visualisation", "Creative Thinking", "Communication"],
        "interests": ["AI tools", "product analytics", "user behaviour"],
        "hours_per_week": 4,
    },
    "support-engineer": {
        "label": "Support engineer considering cloud data or cyber",
        "current_role": "Support Engineer",
        "skills": ["Python Programming", "Technical Writing", "Problem Solving", "API Integration", "Log Analysis"],
        "interests": ["cloud", "security", "automation"],
        "hours_per_week": 6,
    },
}

LEARNING_RESOURCES = {
    "Python Programming": ["Automate a CSV/reporting task with Python", "Write tests for one script"],
    "SQL": ["Practise joins/window functions on a public dataset", "Explain one query plan in plain English"],
    "Data Visualisation": ["Rebuild one workplace dashboard with fewer charts", "Add annotations explaining the decision"],
    "AI Literacy": ["Complete an AI literacy module", "Document risks and safeguards for one AI workflow"],
    "Prompt Evaluation": ["Create 10 test cases for an AI assistant", "Score outputs for usefulness, safety and accuracy"],
    "Product Analytics": ["Define activation/retention metrics for a simple product", "Run a before/after analysis"],
    "Responsible AI": ["Write a privacy and bias checklist", "Add human review checkpoints"],
    "API Integration": ["Call one public API from Python", "Handle errors, retries and logging"],
    "Workflow Automation": ["Map a manual workflow", "Automate the smallest painful step first"],
    "Testing": ["Add unit tests around core logic", "Test happy path and one edge case"],
    "Cloud Platforms": ["Deploy a small service", "Explain storage, compute and monitoring choices"],
    "Data Engineering": ["Create an extract-transform-load pipeline", "Add data validation checks"],
    "Data Quality": ["Define quality rules", "Produce a failed-record report"],
    "Cybersecurity Operations": ["Triage sample alerts", "Write an incident timeline"],
    "Log Analysis": ["Parse logs with Python", "Find unusual patterns and explain them"],
    "Incident Response": ["Draft a playbook", "Run a tabletop exercise"],
    "Learning Needs Analysis": ["Interview 3 learners", "Turn needs into measurable outcomes"],
    "Curriculum Design": ["Storyboard a 2-hour module", "Align activities to outcomes"],
    "Assessment Design": ["Create a rubric", "Pilot it on one example"],
    "Sustainability Reporting": ["Map reporting metrics to evidence", "Create an audit trail"],
}
